/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.EcoSystem;
import Business.Menu.Menu;
import Business.Organization;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class RequestLabTestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;    
    private UserAccount userAccount;
    EcoSystem ecosystem;
    Restaurant selectedRest;
    Menu selectedMenu;
    
    /**
     * Creates new form RequestLabTestJPanel
     */
    public RequestLabTestJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem ecosystem) {
        initComponents();        
        this.userProcessContainer = userProcessContainer;        
        this.userAccount = account;
        this.ecosystem = ecosystem;
        
//        valueLabel.setText(account.getUsername());
        populateComboRest();
        if(ecosystem.getRestaurantDirectory().getRestaurantList().size() > 0){
            selectedRest = ecosystem.getRestaurantDirectory().getRestaurantList().get(0);
            populateComboMenu();
            if(selectedRest.getMenuDirectory().getMenuList().size() > 0){
                selectedMenu = selectedRest.getMenuDirectory().getMenuList().get(0);
            }
        }
       
    }

    public void populateComboRest(){
        for(Restaurant r:ecosystem.getRestaurantDirectory().getRestaurantList()){
            comboRest.addItem(r.toString());
        }
    }
    
    public void populateComboMenu(){
        comboMenu.removeAllItems();
        for(Menu m:selectedRest.getMenuDirectory().getMenuList()){
            comboMenu.addItem(m.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOrder = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboRest = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        comboMenu = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOrder.setText("Order");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });
        add(btnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        backJButton.setText("< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        valueLabel.setText("Place an Order");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 130, -1));

        jLabel2.setText("Select Restaurant:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 30));

        comboRest.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboRestPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        add(comboRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 220, -1));

        jLabel3.setText("Select Menu:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 30));

        comboMenu.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboMenuPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        add(comboMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 220, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        if(selectedRest == null || selectedMenu == null){
            JOptionPane.showMessageDialog(this, "Please select a menu.");
            return;
        }else{
            LabTestWorkRequest ltwq = (LabTestWorkRequest) selectedRest.getWorkQueue().addRequest();
            ltwq.setSender(userAccount.getEmployee());
            ltwq.setReceiver(selectedRest);
//            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");            
            ltwq.setRequestDate(new Date());
            ltwq.setMenu(selectedMenu);
            ltwq.setStatus("Waiting for reply");
            
            ecosystem.getCustomerDirectory().searchCustomer(userAccount.getEmployee()).addRequest(ltwq);
            
            JOptionPane.showMessageDialog(this, "Order successfully.");
            back();
        }
        
        
    }//GEN-LAST:event_btnOrderActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        back();
        
    }//GEN-LAST:event_backJButtonActionPerformed

    private void comboRestPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboRestPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if(comboRest.getSelectedItem() == null){
            comboMenu.removeAllItems();
        }else{
            selectedRest = ecosystem.getRestaurantDirectory().searchRestaurant(comboRest.getSelectedItem().toString());
            populateComboMenu();
        }
        
    }//GEN-LAST:event_comboRestPopupMenuWillBecomeInvisible

    private void comboMenuPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboMenuPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if(comboMenu.getSelectedItem() == null){
            selectedMenu = null;
        }else{
            selectedMenu = selectedRest.getMenuDirectory().searchMenu(comboMenu.getSelectedItem().toString());
        }

    }//GEN-LAST:event_comboMenuPopupMenuWillBecomeInvisible

    public void back(){
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerAreaJPanel dwjp = (CustomerAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.last(userProcessContainer);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnOrder;
    private javax.swing.JComboBox<String> comboMenu;
    private javax.swing.JComboBox<String> comboRest;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
