/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Restaurant.Restaurant;
import Business.Role.AdminRole;
import Business.Role.Role;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author changxu
 */
public class ModifyRestaurantJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ModifyRestaurantJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    Restaurant restaurant;
    Role employeeRole;
    Employee preAdmin;
    
    public ModifyRestaurantJPanel(JPanel userProcessContainer, EcoSystem ecosystem, Restaurant restaurant) {
        initComponents();
        this.restaurant = restaurant;
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        
        populateCombo();
        jTextField1.setText(restaurant.getName());
        jComboBox1.setSelectedItem(restaurant.getAdminEmployee().toString() + "(ID:"+restaurant.getAdminEmployee().getId()+")");
        preAdmin = restaurant.getAdminEmployee();
    }
    
    public void populateCombo(){
        for(Employee e: ecosystem.getEmployeeDirectory().getEmployeeList()){
            if(e.getRole().getClass() == AdminRole.class){
                AdminRole adminRole = (AdminRole) e.getRole();
                if(adminRole.getRestaurant() == null){
                    jComboBox1.addItem(e.toString() + "(ID:"+e.getId()+")");
                    employeeRole = e.getRole();                    
                }
            }
        }
        jComboBox1.addItem(restaurant.getAdminEmployee().toString() + "(ID:"+restaurant.getAdminEmployee().getId()+")");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        jLabel1.setText("Modify Restaurant");

        jLabel2.setText("Restaurant Name:");

        jLabel3.setText("Restaurant Admin:");

        btnBack.setText("< back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(jLabel1))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(175, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        back();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().isBlank() || jComboBox1.getSelectedItem() == null){
            JOptionPane.showMessageDialog(this, "Please complete all information before saving.");
            return;
        }

        String name = jTextField1.getText();
        int selectedID = Integer.parseInt(jComboBox1.getSelectedItem().toString().substring(jComboBox1.getSelectedItem().toString().indexOf(":")+1, jComboBox1.getSelectedItem().toString().indexOf(")")));
        Employee selectedE = ecosystem.getEmployeeDirectory().searchEmployee(selectedID, employeeRole);
        
        restaurant.setName(name);
        
        if(preAdmin != selectedE){
            restaurant.setAdminEmployee(selectedE);
            AdminRole adminRole = (AdminRole) selectedE.getRole();
            adminRole.setRestaurant(restaurant);
            
            AdminRole preRole = (AdminRole) preAdmin.getRole();
            preRole.setRestaurant(null);
        }
        
        JOptionPane.showMessageDialog(this, "Modify restaurant successfully.");
        back();
    }//GEN-LAST:event_btnSaveActionPerformed

    public void back(){
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageRestaurantJPanel mrjp = (ManageRestaurantJPanel) component;
        mrjp.refreshTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.last(userProcessContainer);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
