/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Restaurant.Restaurant;
import Business.Role.Role;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author changxu
 */
public class RestaurantOrderDetailJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RestaurantOrderDetailJPanel
     */
    JPanel userProcessContainer;
    LabTestWorkRequest ltwr;
    Restaurant restaurant;
    EcoSystem ecosystem;
    Role employeeRole;
    DeliveryMan oldDeliver;
    
    public RestaurantOrderDetailJPanel(JPanel userProcessContainer, LabTestWorkRequest ltwr, Restaurant restaurant, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ltwr = ltwr;
        this.restaurant = restaurant;
        this.ecosystem = ecosystem;

        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");                    
        txtDate.setText(df.format(ltwr.getRequestDate()));
        txtMenu.setText(ltwr.getMenu().toString());
        txtRestaurant.setText(ltwr.getReceiver().toString());
        
        if(ltwr.getMessage() != null){
            txtComment.setText(ltwr.getMessage());
        }        
        
        comboStatus.setSelectedItem(ltwr.getStatus());
        
        if(ltwr.getDeliveryMan() != null){
            populateComboDeliver();
            comboDeliver.setSelectedItem(ltwr.getDeliveryMan());
            oldDeliver = ltwr.getDeliveryMan();
        }else{
            oldDeliver = null;
        }        
        comboStatus.setEnabled(false);
        comboDeliver.setEnabled(false);        
        
    }

    public void populateComboDeliver(){
        for(DeliveryMan dm:ecosystem.getDeliveryManDirectory().getDeliveryManList()){
            if(dm.getRestaurant() == restaurant){
                comboDeliver.addItem(dm.getEmployee().toString() + "(ID:"+dm.getEmployee().getId()+")");
                employeeRole = dm.getEmployee().getRole();
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valueLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        txtRestaurant = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtMenu = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtComment = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox<>();
        comboDeliver = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();

        valueLabel.setText("View Order Detail");

        jLabel4.setText("Request Date:");

        txtDate.setEditable(false);

        jLabel5.setText("Restaurant:");

        btnAdd.setText("Make Changes");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        txtRestaurant.setEditable(false);

        backJButton.setText("< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Menu:");

        txtMenu.setEditable(false);

        jLabel7.setText("Status:");

        jLabel8.setText("Comment:");

        txtComment.setEditable(false);

        jLabel9.setText("Delivery Man:");

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Waiting for reply", "Accepted", "Rejected", "Processing", "Finished" }));
        comboStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboStatusActionPerformed(evt);
            }
        });

        btnSave.setText("Save Changes");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtComment, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addGap(18, 18, 18)
                                .addComponent(btnSave))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(comboDeliver, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, 282, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(backJButton)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(backJButton)
                .addGap(18, 18, 18)
                .addComponent(valueLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(comboDeliver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnSave))
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        btnSave.setEnabled(true);
        comboStatus.setEnabled(true);
        comboDeliver.setEnabled(true);        

        comboStatus.setSelectedItem(ltwr.getStatus());
        populateComboDeliver();
        comboDeliver.setSelectedItem(ltwr.getDeliveryMan());
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        back();
    }//GEN-LAST:event_backJButtonActionPerformed

    private void comboStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboStatusActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(comboStatus.getSelectedItem() == null){
            JOptionPane.showMessageDialog(this, "Please ensure to select status.");
            return;
        }
        if(comboStatus.getSelectedItem().toString().equals("Accepted") & comboDeliver.getSelectedItem() == null){
            JOptionPane.showMessageDialog(this, "Please select a delivery man.");
            return;
        }
        ltwr.setStatus(comboStatus.getSelectedItem().toString());
        
        if(comboDeliver.getSelectedItem() != null){
            int selectedID = Integer.parseInt(comboDeliver.getSelectedItem().toString().substring(comboDeliver.getSelectedItem().toString().indexOf(":")+1, comboDeliver.getSelectedItem().toString().indexOf(")")));
            Employee selectedE = ecosystem.getEmployeeDirectory().searchEmployee(selectedID, employeeRole);
            DeliveryMan selectedD = ecosystem.getDeliveryManDirectory().searchDeliveryMan(selectedE);        
            
            if( oldDeliver != selectedD){
                ltwr.setDeliveryMan(selectedD);
                selectedD.getRequestList().add(ltwr);
            }
        }
                
        
        JOptionPane.showMessageDialog(this, "Order save successfully.");
        back();
    }//GEN-LAST:event_btnSaveActionPerformed

    public void back(){
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        RestaurantOrderJPanel rojp = (RestaurantOrderJPanel) component;
        rojp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.last(userProcessContainer);

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboDeliver;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtComment;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtMenu;
    private javax.swing.JTextField txtRestaurant;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
